### ISSUE TITLE
Resulting object is not of type glm/lm and cannot be used to call predict

### ISSUE THREAD

**Issue by inigobermejo** [IKNL/vtg.glm#1]
Once the model has been trained, the resulting object could in principle be used as input parameter to R's predict function, but it does not work because the object is not of glm/lm type and it's missing some of the attributes of glm/lm objects such as terms and rank.

**Comment by frankcorneliusmartin** [comment]
Hi @inigobermejo, I think we have a piece of code that does this. This has been written bij @matteo-cellamare. Ill try to locate it.

**Comment by frankcorneliusmartin** [comment]
Hmm not sure why it is not part of this repo. But i think this is the bit of code you are looking for?:
https://github.com/IKNL/vtg.pss/blob/master/src/R/as.GLM.R

Let me know if this is not the case.

**Comment by matteo-cellamare** [comment]
Hi, the function doesn't return a GLM object because theoutput should be in a csv file and its usage is not limited to R. 
if you apply the function as.GLM(object) to the output it will be trasnform into a glm object that works with the predict function

**Comment by inigobermejo** [comment]
Thanks, both for the prompt response. Yes, indeed, as.GLM is what I needed. I still believe it would make more sense if the dglm R function returned a glm object or at least for the as.GLM function to be part of this package, but that's up to you. Thanks again!

**Comment by frankcorneliusmartin** [comment]
I agree with that. Ill reopen the issue. Feel free to submit a PR.

**Comment by frankcorneliusmartin** [comment]
fixed in 7ffd867d9849c69159f1767bc10dcd57e50a924c
